---

- name: Install dependencies
  apt: pkg=python-pip
  when: ansible_os_family == 'Debian'

- name: Install supervisor
  pip: name=supervisor

- name: Install superlance
  pip: name=superlance
  when: supervisor_superlance

- name: Prepare directories
  file: state=directory path={{item}}
  with_items:
    - "{{supervisor_cfgdir}}"
    - "{{supervisor_logdir}}"
    - "{{supervisor_incdir}}"

- name: Configure supervisor - pt. 1
  template: src=supervisor.j2 dest=/etc/init.d/supervisor owner=root group=root mode=0755

- name: Configure supervisor
  template: src=supervisord.conf.j2 dest={{supervisor_cfgdir}}/supervisord.conf owner=root group=root mode=0644
  notify:
    - supervisor reread
    - supervisor restart

- name: Ensure the supervisor is started
  service: name=supervisor state=started
